// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOxUKCT-zdrjxx97mMNteCSlCUMb1Sdq0',
    appId: '1:368154495869:web:644ff4b361adf2f7305a14',
    messagingSenderId: '368154495869',
    projectId: 'fir-auth-fba1c',
    authDomain: 'fir-auth-fba1c.firebaseapp.com',
    storageBucket: 'fir-auth-fba1c.appspot.com',
    measurementId: 'G-60BHVBY8W9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXuCqxir8ml8jqvZybN9bwh8qXt930j5g',
    appId: '1:368154495869:android:7b68f6660dbcddca305a14',
    messagingSenderId: '368154495869',
    projectId: 'fir-auth-fba1c',
    storageBucket: 'fir-auth-fba1c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsijcLDbUh-XTwxGGyaGqrYE-CMtX_c3c',
    appId: '1:368154495869:ios:5bd4d3c1278de17f305a14',
    messagingSenderId: '368154495869',
    projectId: 'fir-auth-fba1c',
    storageBucket: 'fir-auth-fba1c.appspot.com',
    iosBundleId: 'com.example.dashboard',
  );
}
